export const SET_INFORMATION = 'SET_INFORMATION';
export const GET_CLAIM_SETTLEMENT = 'GET_CLAIM_SETTLEMENT';
export const GET_CLAIM_LIST = 'GET_CLAIM_LIST';
export const GET_CLAIM_DETAIL = 'GET_CLAIM_DETAIL';
