export const SET_HEALTHY_FILE = 'SET_HEALTHY_FILE';
export const SET_SHOW_NUMBER = 'SET_SHOW_NUMBER';
export const GET_HEALTHY_FILE = 'GET_HEALTHY_FILE';
export const GET_OLD_HEALTHY_FILE = 'GET_OLD_HEALTHY_FILE';
export const INIT_OLD_HEALTHY_FILE = 'INIT_OLD_HEALTHY_FILE';
