export const GET_DIAGNOSE_LIST = 'GET_DIAGNOSE_LIST';
export const CHANGE_RECORD_LIST = 'CHANGE_RECORD_LIST';
export const SET_SERVICE_RECORD_ID = 'SET_SERVICE_RECORD_ID';
export const SET_CHAT_INFO = 'SET_CHAT_INFO';
