export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL';
export const GET_PRODUCT_LIST = 'GET_PRODUCT_LIST';
export const GET_USER_SCORE = 'GET_USER_SCORE';
export const GET_RECORDS_LIST = 'GET_RECORDS_LIST';
export const GET_MAIN_PRODUCT_LIST = 'GET_MAIN_PRODUCT_LIST';
export const RESET_USER_SCREORE = 'RESET_USER_SCREORE';
export const SET_DIS_BUY = 'SET_DIS_BUY';
