export const GET_SERVICE_DETAIL = 'GET_SERVICE_DETAIL';
export const GET_EVALUATE_DETAIL = 'GET_EVALUATE_DETAIL';
export const GET_CONTINUE_LIST = 'GET_CONTINUE_LIST';
export const GET_COMMODITY_EXCHANGE = 'GET_COMMODITY_EXCHANGE';
export const GET_SELECT_ADDRESS = 'GET_SELECT_ADDRESS';
